/**
 * @description exhaustive list of supported languages for MKVToolNix,
 * acquired from https://gitlab.com/mbunkus/mkvtoolnix repo, in file:
 * mkvtoolnix-main/src/common/iso639_language_list.cpp
 */

const supportedLanguages = [
  { key: 'abk', text:'Abkhazian' },
  { key: 'ace', text:'Achinese' },
  { key: 'ach', text:'Acoli' },
  { key: 'ada', text:'Adangme' },
  { key: 'ady', text:'Adyghe; Adygei' },
  { key: 'aar', text:'Afar' },
  { key: 'afh', text:'Afrihili' },
  { key: 'afr', text:'Afrikaans' },
  { key: 'afa', text:'Afro-Asiatic languages' },
  { key: 'ain', text:'Ainu' },
  { key: 'aka', text:'Akan' },
  { key: 'akk', text:'Akkadian' },
  { key: 'alb', text:'Albanian' },
  { key: 'ale', text:'Aleut' },
  { key: 'alg', text:'Algonquian languages' },
  { key: 'tut', text:'Altaic languages' },
  { key: 'amh', text:'Amharic' },
  { key: 'anp', text:'Angika' },
  { key: 'apa', text:'Apache languages' },
  { key: 'ara', text:'Arabic' },
  { key: 'arg', text:'Aragonese' },
  { key: 'arp', text:'Arapaho' },
  { key: 'arw', text:'Arawak' },
  { key: 'arm', text:'Armenian' },
  { key: 'rup', text:'Aromanian; Arumanian; Macedo-Romanian' },
  { key: 'art', text:'Artificial languages' },
  { key: 'asm', text:'Assamese' },
  { key: 'ast', text:'Asturian; Bable; Leonese; Asturleonese' },
  { key: 'ath', text:'Athapascan languages' },
  { key: 'aus', text:'Australian languages' },
  { key: 'map', text:'Austronesian languages' },
  { key: 'ava', text:'Avaric' },
  { key: 'ave', text:'Avestan' },
  { key: 'awa', text:'Awadhi' },
  { key: 'aym', text:'Aymara' },
  { key: 'aze', text:'Azerbaijani' },
  { key: 'ban', text:'Balinese' },
  { key: 'bat', text:'Baltic languages' },
  { key: 'bal', text:'Baluchi' },
  { key: 'bam', text:'Bambara' },
  { key: 'bai', text:'Bamileke languages' },
  { key: 'bad', text:'Banda languages' },
  { key: 'bnt', text:'Bantu (Other)' },
  { key: 'bas', text:'Basa' },
  { key: 'bak', text:'Bashkir' },
  { key: 'baq', text:'Basque' },
  { key: 'btk', text:'Batak languages' },
  { key: 'bej', text:'Beja; Bedawiyet' },
  { key: 'bel', text:'Belarusian' },
  { key: 'bem', text:'Bemba' },
  { key: 'ben', text:'Bengali' },
  { key: 'ber', text:'Berber languages' },
  { key: 'bho', text:'Bhojpuri' },
  { key: 'bih', text:'Bihari languages' },
  { key: 'bik', text:'Bikol' },
  { key: 'bin', text:'Bini; Edo' },
  { key: 'bis', text:'Bislama' },
  { key: 'byn', text:'Blin; Bilin' },
  { key: 'zbl', text:'Blissymbols; Blissymbolics; Bliss' },
  { key: 'nob', text:'Bokmål, Norwegian; Norwegian Bokmål' },
  { key: 'bos', text:'Bosnian' },
  { key: 'bra', text:'Braj' },
  { key: 'bre', text:'Breton' },
  { key: 'bug', text:'Buginese' },
  { key: 'bul', text:'Bulgarian' },
  { key: 'bua', text:'Buriat' },
  { key: 'bur', text:'Burmese' },
  { key: 'cad', text:'Caddo' },
  { key: 'cat', text:'Catalan; Valencian' },
  { key: 'cau', text:'Caucasian languages' },
  { key: 'ceb', text:'Cebuano' },
  { key: 'cel', text:'Celtic languages' },
  { key: 'cai', text:'Central American Indian languages' },
  { key: 'khm', text:'Central Khmer' },
  { key: 'chg', text:'Chagatai' },
  { key: 'cmc', text:'Chamic languages' },
  { key: 'cha', text:'Chamorro' },
  { key: 'che', text:'Chechen' },
  { key: 'chr', text:'Cherokee' },
  { key: 'chy', text:'Cheyenne' },
  { key: 'chb', text:'Chibcha' },
  { key: 'nya', text:'Chichewa; Chewa; Nyanja' },
  { key: 'chi', text:'Chinese' },
  { key: 'chn', text:'Chinook jargon' },
  { key: 'chp', text:'Chipewyan; Dene Suline' },
  { key: 'cho', text:'Choctaw' },
  { key: 'chu', text:'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic' },
  { key: 'chk', text:'Chuukese' },
  { key: 'chv', text:'Chuvash' },
  { key: 'nwc', text:'Classical Newari; Old Newari; Classical Nepal Bhasa' },
  { key: 'syc', text:'Classical Syriac' },
  { key: 'cop', text:'Coptic' },
  { key: 'cor', text:'Cornish' },
  { key: 'cos', text:'Corsican' },
  { key: 'cre', text:'Cree' },
  { key: 'mus', text:'Creek' },
  { key: 'crp', text:'Creoles and pidgins' },
  { key: 'cpe', text:'Creoles and pidgins, English based' },
  { key: 'cpf', text:'Creoles and pidgins, French-based' },
  { key: 'cpp', text:'Creoles and pidgins, Portuguese-based' },
  { key: 'crh', text:'Crimean Tatar; Crimean Turkish' },
  { key: 'hrv', text:'Croatian' },
  { key: 'cus', text:'Cushitic languages' },
  { key: 'cze', text:'Czech' },
  { key: 'dak', text:'Dakota' },
  { key: 'dan', text:'Danish' },
  { key: 'dar', text:'Dargwa' },
  { key: 'del', text:'Delaware' },
  { key: 'din', text:'Dinka' },
  { key: 'div', text:'Divehi; Dhivehi; Maldivian' },
  { key: 'doi', text:'Dogri' },
  { key: 'dgr', text:'Dogrib' },
  { key: 'dra', text:'Dravidian languages' },
  { key: 'dua', text:'Duala' },
  { key: 'dum', text:'Dutch, Middle (ca. 1050-1350)' },
  { key: 'dut', text:'Dutch; Flemish' },
  { key: 'dyu', text:'Dyula' },
  { key: 'dzo', text:'Dzongkha' },
  { key: 'frs', text:'Eastern Frisian' },
  { key: 'efi', text:'Efik' },
  { key: 'egy', text:'Egyptian (Ancient)' },
  { key: 'eka', text:'Ekajuk' },
  { key: 'elx', text:'Elamite' },
  { key: 'eng', text:'English' },
  { key: 'enm', text:'English, Middle (1100-1500)' },
  { key: 'ang', text:'English, Old (ca. 450-1100)' },
  { key: 'myv', text:'Erzya' },
  { key: 'epo', text:'Esperanto' },
  { key: 'est', text:'Estonian' },
  { key: 'ewe', text:'Ewe' },
  { key: 'ewo', text:'Ewondo' },
  { key: 'fan', text:'Fang' },
  { key: 'fat', text:'Fanti' },
  { key: 'fao', text:'Faroese' },
  { key: 'fij', text:'Fijian' },
  { key: 'fil', text:'Filipino; Pilipino' },
  { key: 'fin', text:'Finnish' },
  { key: 'fiu', text:'Finno-Ugrian languages' },
  { key: 'fon', text:'Fon' },
  { key: 'fre', text:'French' },
  { key: 'frm', text:'French, Middle (ca. 1400-1600)' },
  { key: 'fro', text:'French, Old (842-ca. 1400)' },
  { key: 'fur', text:'Friulian' },
  { key: 'ful', text:'Fulah' },
  { key: 'gaa', text:'Ga' },
  { key: 'gla', text:'Gaelic; Scottish Gaelic' },
  { key: 'car', text:'Galibi Carib' },
  { key: 'glg', text:'Galician' },
  { key: 'lug', text:'Ganda' },
  { key: 'gay', text:'Gayo' },
  { key: 'gba', text:'Gbaya' },
  { key: 'gez', text:'Geez' },
  { key: 'geo', text:'Georgian' },
  { key: 'ger', text:'German' },
  { key: 'gmh', text:'German, Middle High (ca. 1050-1500)' },
  { key: 'goh', text:'German, Old High (ca. 750-1050)' },
  { key: 'gem', text:'Germanic languages' },
  { key: 'gil', text:'Gilbertese' },
  { key: 'gon', text:'Gondi' },
  { key: 'gor', text:'Gorontalo' },
  { key: 'got', text:'Gothic' },
  { key: 'grb', text:'Grebo' },
  { key: 'grc', text:'Greek, Ancient (to 1453)' },
  { key: 'gre', text:'Greek, Modern (1453-)' },
  { key: 'grn', text:'Guarani' },
  { key: 'guj', text:'Gujarati' },
  { key: 'gwi', text:'Gwich\'in' },
  { key: 'hai', text:'Haida' },
  { key: 'hat', text:'Haitian; Haitian Creole' },
  { key: 'hau', text:'Hausa' },
  { key: 'haw', text:'Hawaiian' },
  { key: 'heb', text:'Hebrew' },
  { key: 'her', text:'Herero' },
  { key: 'hil', text:'Hiligaynon' },
  { key: 'him', text:'Himachali languages; Western Pahari languages' },
  { key: 'hin', text:'Hindi' },
  { key: 'hmo', text:'Hiri Motu' },
  { key: 'hit', text:'Hittite' },
  { key: 'hmn', text:'Hmong; Mong' },
  { key: 'hun', text:'Hungarian' },
  { key: 'hup', text:'Hupa' },
  { key: 'iba', text:'Iban' },
  { key: 'ice', text:'Icelandic' },
  { key: 'ido', text:'Ido' },
  { key: 'ibo', text:'Igbo' },
  { key: 'ijo', text:'Ijo languages' },
  { key: 'ilo', text:'Iloko' },
  { key: 'smn', text:'Inari Sami' },
  { key: 'inc', text:'Indic languages' },
  { key: 'ine', text:'Indo-European languages' },
  { key: 'ind', text:'Indonesian' },
  { key: 'inh', text:'Ingush' },
  { key: 'ina', text:'Interlingua (International Auxiliary Language Association)' },
  { key: 'ile', text:'Interlingue; Occidental' },
  { key: 'iku', text:'Inuktitut' },
  { key: 'ipk', text:'Inupiaq' },
  { key: 'ira', text:'Iranian languages' },
  { key: 'gle', text:'Irish' },
  { key: 'mga', text:'Irish, Middle (900-1200)' },
  { key: 'sga', text:'Irish, Old (to 900)' },
  { key: 'iro', text:'Iroquoian languages' },
  { key: 'ita', text:'Italian' },
  { key: 'jpn', text:'Japanese' },
  { key: 'jav', text:'Javanese' },
  { key: 'jrb', text:'Judeo-Arabic' },
  { key: 'jpr', text:'Judeo-Persian' },
  { key: 'kbd', text:'Kabardian' },
  { key: 'kab', text:'Kabyle' },
  { key: 'kac', text:'Kachin; Jingpho' },
  { key: 'kal', text:'Kalaallisut; Greenlandic' },
  { key: 'xal', text:'Kalmyk; Oirat' },
  { key: 'kam', text:'Kamba' },
  { key: 'kan', text:'Kannada' },
  { key: 'kau', text:'Kanuri' },
  { key: 'kaa', text:'Kara-Kalpak' },
  { key: 'krc', text:'Karachay-Balkar' },
  { key: 'krl', text:'Karelian' },
  { key: 'kar', text:'Karen languages' },
  { key: 'kas', text:'Kashmiri' },
  { key: 'csb', text:'Kashubian' },
  { key: 'kaw', text:'Kawi' },
  { key: 'kaz', text:'Kazakh' },
  { key: 'kha', text:'Khasi' },
  { key: 'khi', text:'Khoisan languages' },
  { key: 'kho', text:'Khotanese; Sakan' },
  { key: 'kik', text:'Kikuyu; Gikuyu' },
  { key: 'kmb', text:'Kimbundu' },
  { key: 'kin', text:'Kinyarwanda' },
  { key: 'kir', text:'Kirghiz; Kyrgyz' },
  { key: 'tlh', text:'Klingon; tlhIngan-Hol' },
  { key: 'kom', text:'Komi' },
  { key: 'kon', text:'Kongo' },
  { key: 'kok', text:'Konkani' },
  { key: 'kor', text:'Korean' },
  { key: 'kos', text:'Kosraean' },
  { key: 'kpe', text:'Kpelle' },
  { key: 'kro', text:'Kru languages' },
  { key: 'kua', text:'Kuanyama; Kwanyama' },
  { key: 'kum', text:'Kumyk' },
  { key: 'kur', text:'Kurdish' },
  { key: 'kru', text:'Kurukh' },
  { key: 'kut', text:'Kutenai' },
  { key: 'lad', text:'Ladino' },
  { key: 'lah', text:'Lahnda' },
  { key: 'lam', text:'Lamba' },
  { key: 'day', text:'Land Dayak languages' },
  { key: 'lao', text:'Lao' },
  { key: 'lat', text:'Latin' },
  { key: 'lav', text:'Latvian' },
  { key: 'lez', text:'Lezghian' },
  { key: 'lim', text:'Limburgan; Limburger; Limburgish' },
  { key: 'lin', text:'Lingala' },
  { key: 'lit', text:'Lithuanian' },
  { key: 'jbo', text:'Lojban' },
  { key: 'nds', text:'Low German; Low Saxon; German, Low; Saxon, Low' },
  { key: 'dsb', text:'Lower Sorbian' },
  { key: 'loz', text:'Lozi' },
  { key: 'lub', text:'Luba-Katanga' },
  { key: 'lua', text:'Luba-Lulua' },
  { key: 'lui', text:'Luiseno' },
  { key: 'smj', text:'Lule Sami' },
  { key: 'lun', text:'Lunda' },
  { key: 'luo', text:'Luo (Kenya and Tanzania)' },
  { key: 'lus', text:'Lushai' },
  { key: 'ltz', text:'Luxembourgish; Letzeburgesch' },
  { key: 'mac', text:'Macedonian' },
  { key: 'mad', text:'Madurese' },
  { key: 'mag', text:'Magahi' },
  { key: 'mai', text:'Maithili' },
  { key: 'mak', text:'Makasar' },
  { key: 'mlg', text:'Malagasy' },
  { key: 'may', text:'Malay' },
  { key: 'mal', text:'Malayalam' },
  { key: 'mlt', text:'Maltese' },
  { key: 'mnc', text:'Manchu' },
  { key: 'mdr', text:'Mandar' },
  { key: 'man', text:'Mandingo' },
  { key: 'mni', text:'Manipuri' },
  { key: 'mno', text:'Manobo languages' },
  { key: 'glv', text:'Manx' },
  { key: 'mao', text:'Maori' },
  { key: 'arn', text:'Mapudungun; Mapuche' },
  { key: 'mar', text:'Marathi' },
  { key: 'chm', text:'Mari' },
  { key: 'mah', text:'Marshallese' },
  { key: 'mwr', text:'Marwari' },
  { key: 'mas', text:'Masai' },
  { key: 'myn', text:'Mayan languages' },
  { key: 'men', text:'Mende' },
  { key: 'mic', text:'Mi\'kmaq; Micmac' },
  { key: 'min', text:'Minangkabau' },
  { key: 'mwl', text:'Mirandese' },
  { key: 'moh', text:'Mohawk' },
  { key: 'mdf', text:'Moksha' },
  { key: 'mkh', text:'Mon-Khmer languages' },
  { key: 'lol', text:'Mongo' },
  { key: 'mon', text:'Mongolian' },
  { key: 'mos', text:'Mossi' },
  { key: 'mul', text:'Multiple languages' },
  { key: 'mun', text:'Munda languages' },
  { key: 'nqo', text:'N\'Ko' },
  { key: 'nah', text:'Nahuatl languages' },
  { key: 'nau', text:'Nauru' },
  { key: 'nav', text:'Navajo; Navaho' },
  { key: 'nde', text:'Ndebele, North; North Ndebele' },
  { key: 'nbl', text:'Ndebele, South; South Ndebele' },
  { key: 'ndo', text:'Ndonga' },
  { key: 'nap', text:'Neapolitan' },
  { key: 'new', text:'Nepal Bhasa; Newari' },
  { key: 'nep', text:'Nepali' },
  { key: 'nia', text:'Nias' },
  { key: 'nic', text:'Niger-Kordofanian languages' },
  { key: 'ssa', text:'Nilo-Saharan languages' },
  { key: 'niu', text:'Niuean' },
  { key: 'zxx', text:'No linguistic content; Not applicable' },
  { key: 'nog', text:'Nogai' },
  { key: 'non', text:'Norse, Old' },
  { key: 'nai', text:'North American Indian languages' },
  { key: 'frr', text:'Northern Frisian' },
  { key: 'sme', text:'Northern Sami' },
  { key: 'nno', text:'Norwegian Nynorsk; Nynorsk, Norwegian' },
  { key: 'nor', text:'Norwegian' },
  { key: 'nub', text:'Nubian languages' },
  { key: 'nym', text:'Nyamwezi' },
  { key: 'nyn', text:'Nyankole' },
  { key: 'nyo', text:'Nyoro' },
  { key: 'nzi', text:'Nzima' },
  { key: 'oci', text:'Occitan (post 1500); Provençal' },
  { key: 'arc', text:'Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)' },
  { key: 'oji', text:'Ojibwa' },
  { key: 'ori', text:'Oriya' },
  { key: 'orm', text:'Oromo' },
  { key: 'osa', text:'Osage' },
  { key: 'oss', text:'Ossetian; Ossetic' },
  { key: 'oto', text:'Otomian languages' },
  { key: 'pal', text:'Pahlavi' },
  { key: 'pau', text:'Palauan' },
  { key: 'pli', text:'Pali' },
  { key: 'pam', text:'Pampanga; Kapampangan' },
  { key: 'pag', text:'Pangasinan' },
  { key: 'pan', text:'Panjabi; Punjabi' },
  { key: 'pap', text:'Papiamento' },
  { key: 'paa', text:'Papuan languages' },
  { key: 'nso', text:'Pedi; Sepedi; Northern Sotho' },
  { key: 'per', text:'Persian' },
  { key: 'peo', text:'Persian, Old (ca. 600-400 B.C.)' },
  { key: 'phi', text:'Philippine languages' },
  { key: 'phn', text:'Phoenician' },
  { key: 'pon', text:'Pohnpeian' },
  { key: 'pol', text:'Polish' },
  { key: 'por', text:'Portuguese' },
  { key: 'pra', text:'Prakrit languages' },
  { key: 'pro', text:'Provençal, Old (to 1500)' },
  { key: 'pus', text:'Pushto; Pashto' },
  { key: 'que', text:'Quechua' },
  { key: 'raj', text:'Rajasthani' },
  { key: 'rap', text:'Rapanui' },
  { key: 'rar', text:'Rarotongan; Cook Islands Maori' },
  { key: 'roa', text:'Romance languages' },
  { key: 'rum', text:'Romanian; Moldavian; Moldovan' },
  { key: 'roh', text:'Romansh' },
  { key: 'rom', text:'Romany' },
  { key: 'run', text:'Rundi' },
  { key: 'rus', text:'Russian' },
  { key: 'sal', text:'Salishan languages' },
  { key: 'sam', text:'Samaritan Aramaic' },
  { key: 'smi', text:'Sami languages' },
  { key: 'smo', text:'Samoan' },
  { key: 'sad', text:'Sandawe' },
  { key: 'sag', text:'Sango' },
  { key: 'san', text:'Sanskrit' },
  { key: 'sat', text:'Santali' },
  { key: 'srd', text:'Sardinian' },
  { key: 'sas', text:'Sasak' },
  { key: 'sco', text:'Scots' },
  { key: 'sel', text:'Selkup' },
  { key: 'sem', text:'Semitic languages' },
  { key: 'srp', text:'Serbian' },
  { key: 'srr', text:'Serer' },
  { key: 'shn', text:'Shan' },
  { key: 'sna', text:'Shona' },
  { key: 'iii', text:'Sichuan Yi; Nuosu' },
  { key: 'scn', text:'Sicilian' },
  { key: 'sid', text:'Sidamo' },
  { key: 'sgn', text:'Sign Languages' },
  { key: 'bla', text:'Siksika' },
  { key: 'snd', text:'Sindhi' },
  { key: 'sin', text:'Sinhala; Sinhalese' },
  { key: 'sit', text:'Sino-Tibetan languages' },
  { key: 'sio', text:'Siouan languages' },
  { key: 'sms', text:'Skolt Sami' },
  { key: 'den', text:'Slave (Athapascan)' },
  { key: 'sla', text:'Slavic languages' },
  { key: 'slo', text:'Slovak' },
  { key: 'slv', text:'Slovenian' },
  { key: 'sog', text:'Sogdian' },
  { key: 'som', text:'Somali' },
  { key: 'son', text:'Songhai languages' },
  { key: 'snk', text:'Soninke' },
  { key: 'wen', text:'Sorbian languages' },
  { key: 'sot', text:'Sotho, Southern' },
  { key: 'sai', text:'South American Indian (Other)' },
  { key: 'alt', text:'Southern Altai' },
  { key: 'sma', text:'Southern Sami' },
  { key: 'spa', text:'Spanish; Castilian' },
  { key: 'srn', text:'Sranan Tongo' },
  { key: 'zgh', text:'Standard Moroccan Tamazight' },
  { key: 'suk', text:'Sukuma' },
  { key: 'sux', text:'Sumerian' },
  { key: 'sun', text:'Sundanese' },
  { key: 'sus', text:'Susu' },
  { key: 'swa', text:'Swahili' },
  { key: 'ssw', text:'Swati' },
  { key: 'swe', text:'Swedish' },
  { key: 'gsw', text:'Swiss German; Alemannic; Alsatian' },
  { key: 'syr', text:'Syriac' },
  { key: 'tgl', text:'Tagalog' },
  { key: 'tah', text:'Tahitian' },
  { key: 'tai', text:'Tai languages' },
  { key: 'tgk', text:'Tajik' },
  { key: 'tmh', text:'Tamashek' },
  { key: 'tam', text:'Tamil' },
  { key: 'tat', text:'Tatar' },
  { key: 'tel', text:'Telugu' },
  { key: 'ter', text:'Tereno' },
  { key: 'tet', text:'Tetum' },
  { key: 'tha', text:'Thai' },
  { key: 'tib', text:'Tibetan' },
  { key: 'tig', text:'Tigre' },
  { key: 'tir', text:'Tigrinya' },
  { key: 'tem', text:'Timne' },
  { key: 'tiv', text:'Tiv' },
  { Key: 'tli', text:'Tlingit' },
  { Key: 'tpi', text:'Tok Pisin' },
  { Key: 'tkl', text:'Tokelau' },
  { Key: 'tog', text:'Tonga (Nyasa)' },
  { Key: 'ton', text:'Tonga (Tonga Islands)' },
  { Key: 'tsi', text:'Tsimshian' },
  { Key: 'tso', text:'Tsonga' },
  { Key: 'tsn', text:'Tswana' },
  { Key: 'tum', text:'Tumbuka' },
  { Key: 'tup', text:'Tupi languages' },
  { Key: 'tur', text:'Turkish' },
  { Key: 'ota', text:'Turkish, Ottoman (1500-1928)' },
  { Key: 'tuk', text:'Turkmen' },
  { Key: 'tvl', text:'Tuvalu' },
  { Key: 'tyv', text:'Tuvinian' },
  { Key: 'twi', text:'Twi' },
  { Key: 'udm', text:'Udmurt' },
  { Key: 'uga', text:'Ugaritic' },
  { Key: 'uig', text:'Uighur; Uyghur' },
  { Key: 'ukr', text:'Ukrainian' },
  { Key: 'umb', text:'Umbundu' },
  { Key: 'mis', text:'Uncoded languages' },
  { Key: 'und', text:'Undetermined' },
  { Key: 'hsb', text:'Upper Sorbian' },
  { Key: 'urd', text:'Urdu' },
  { Key: 'uzb', text:'Uzbek' },
  { Key: 'vai', text:'Vai' },
  { Key: 'ven', text:'Venda' },
  { Key: 'vie', text:'Vietnamese' },
  { Key: 'vol', text:'Volapük' },
  { Key: 'vot', text:'Votic' },
  { Key: 'wak', text:'Wakashan languages' },
  { Key: 'wal', text:'Walamo' },
  { Key: 'wln', text:'Walloon' },
  { Key: 'war', text:'Waray' },
  { Key: 'was', text:'Washo' },
  { Key: 'wel', text:'Welsh' },
  { Key: 'fry', text:'Western Frisian' },
  { Key: 'wol', text:'Wolof' },
  { Key: 'xho', text:'Xhosa' },
  { Key: 'sah', text:'Yakut' },
  { Key: 'yao', text:'Yao' },
  { Key: 'yap', text:'Yapese' },
  { Key: 'yid', text:'Yiddish' },
  { Key: 'yor', text:'Yoruba' },
  { Key: 'ypk', text:'Yupik languages' },
  { Key: 'znd', text:'Zande languages' },
  { Key: 'zap', text:'Zapotec' },
  { Key: 'zza', text:'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki' },
  { Key: 'zen', text:'Zenaga' },
  { Key: 'zha', text:'Zhuang; Chuang' },
  { Key: 'zul', text:'Zulu' },
  { Key: 'zun', text:'Zuni' }
];

export default supportedLanguages;